# This workflow will run tests using node and then publish a package to NPM with semantic release.
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: NPM Publish

on:
  push:
    branches: [master]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@master

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Test
        run: npm install-ci-test

      - name: Build
        run: npm run build

      - name: Install extra semantic release dependencies
        run: npm install --no-save @semantic-release/git

      - name: Release
        uses: codfish/semantic-release-action@v2
        id: semantic
        with:
          plugins: |
            [
              "@semantic-release/commit-analyzer", 
              "@semantic-release/release-notes-generator", 
              "@semantic-release/npm", 
              [
                "@semantic-release/git",
                {
                  message: "chore: ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
                },
              ],
              "@semantic-release/github"
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
