name: NPM Publish

on:
  push:
    branches: [master]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Setup
        run: yarn --immutable

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Add extra semantic release depenencies
        run: yarn add -D @semantic-release/git

      - name: Release
        uses: codfish/semantic-release-action@v1
        with:
          plugins: |
            [
              "@semantic-release/commit-analyzer", 
              "@semantic-release/release-notes-generator", 
              "@semantic-release/npm", 
              [
                "@semantic-release/git",
                {
                  message: "chore: ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
                },
              ],
              "@semantic-release/github"
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
