name: PR Target

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  auto-merge:
    name: Auto Merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.PUSH_TOKEN }}
