name: PR Target

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  auto-merge:
    name: Auto Merge
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.PUSH_TOKEN }}
